/**
 * Tricom API
 * Tricom Telecommunication API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: admin@tricom.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AdministrativeState } from './administrativeState';
import { IPVersion } from './iPVersion';


export class Device {
    id: number;
    deviceId: string;
    deviceType: string;
    deviceNumber: number;
    hostName?: string;
    domainName?: string;
    adminState?: AdministrativeState;
    ipVersionActivated?: IPVersion;
    ipVersionSupported?: IPVersion;
    routerCode?: number;
    qoS?: boolean;
    locationId?: string;
    comment?: string;

    public constructor() {}
}
