/**
 * Tricom API
 * Tricom Telecommunication API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: admin@tricom.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type IPVersion = 'IPv6' | 'IPv4' | 'IPv3';

export const IPVersion = {
    IPv6: 'IPv6' as IPVersion,
    IPv4: 'IPv4' as IPVersion,
    IPv3: 'IPv3' as IPVersion
};

/*export enum IPVersion {
    IPv6,
    IPv4,
    IPv3
}

export namespace IPVersion {
    export function keys() {
        return Object.keys(IPVersion).filter(k => isNaN(Number(k)));
    }
}*/
