/**
 * Tricom API
 * Tricom Telecommunication API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: admin@tricom.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Location { 
    locationId: string;
    address: string;
    contactPhone?: string;
    comment?: string;
}
